language: objective-c
install:
- brew install shellcheck
script:
- make test
notifications:
  slack:
    secure: W/drUsVY+1CehmBDMVchSgz0abNs0W6W6bANDS4nJ8/WC9PzBj6YHNqdd/gNyvZ9oVYWpc1ka29jEVcogIgLMfil+/4+W1aXKnCc7sEgLTIk7jTAs5VE51XI30BeqyFcmq2Ded1+IxQZsCW8ptbp0A/W7D33QHTn/wPIEvYk8pihlHTyD4iE2HJX/jNOI5xk+9saAEE64fNzrPIUK6jAB6891miPCXcp5ncjIli1r1FxgHi7b7W6zmMNYo0P405yxpruYpmbQCsMF/0EWzLlriS+KZznu8d5sdHVQZ1lVxYTkNtskVXCnUlna9nISkkh6ROwofkmmq84TLSK/0XEV7EUD+OobHwj+Ru1IN5eSLk3CI4vkUzTsrjmUgy+eNpKlTpzM5raKvoXGh97vDt4dzOK8ySOvRidt10yV+n50m4+UYaFgqtoo6ho3/SWUUW/tSRBl4HlHIcP0jNXsiwjFUU/B5qY94Lnvm4bZuSdWdAQE/tsVM4YBIKXMU1fNZajZRAQZt9REeTDICsTRQqs4Yhdu3SvcVBp8FeBCLMK+19PtZqICQxIjn4JBndoo61E1yxya3+eMSZMs/da+KgPUXzvaV60Y68Or7uIMF6Lwos30A7UMyVpgkFNF73RUQ3J4VJQSmx74iptl3BntLV7pT+KgE/9RTrrjRvZbaSkL8Q=
