#!/usr/bin/env bash

import_provisions ()
{
    if [ -z "$SCRIPT_DIR" ]
    then
        echo "error: \$SCRIPT_DIR is not defined"
        return 1
    fi

    if [ ! -d "$SCRIPT_DIR/provisions" ]
    then
        echo "error: $SCRIPT_DIR/provisions does not exist"
        return 1
    fi

    local p
    for p in $SCRIPT_DIR/provisions/*.mobileprovision;
    do
        cp "$p" "$HOME/Library/MobileDevice/Provisioning Profiles/"
        echo "${p##*/} imported"
    done
}

delete_provisions ()
{
    if [ -z "$SCRIPT_DIR" ]
    then
        echo "error: \$SCRIPT_DIR is not defined"
        return 1
    fi

    if [ ! -d "$SCRIPT_DIR/provisions" ]
    then
        echo "error: $SCRIPT_DIR/provisions does not exist"
        return 1
    fi

    local p
    for p in $SCRIPT_DIR/provisions/*.mobileprovision;
    do
        rm "$HOME/Library/MobileDevice/Provisioning Profiles/${p##*/}"
    done
}

ls_provisions ()
{
    ls "$HOME/Library/MobileDevice/Provisioning Profiles"
}

usage () {
    echo "Usage: mobileprobvision < --import | --remove | -l >"
    echo ""
    echo "--import - Import provisions under provisions/"
    echo "--remove - Remove imported provisions under provisions/"
    echo "-l       - List all system provisions"
}

main ()
{
    case "$1" in
        --import)
            import_provisions
            ;;
        --remove)
            delete_provisions
            ;;
        -l)
            ls_provisions
            ;;
        *)
            usage
            ;;
    esac
}

main "$@"
