#!/usr/bin/env bash

update_build_number() {
    local build=$1

    if [ -z "$1" ]
    then
        echo "Bypassing update_build_number"
        return
    fi

    if ! echo "$build" | grep -q -E '^[0-9]+$'
    then
        echo "error: Invalid build number specified"
        exit 1
    fi

    xcrun agvtool new-version -all "$build"
}

update_build_number "$@"
